#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : os-service-types
Version  : 1.3.0
Release  : 1
URL      : https://files.pythonhosted.org/packages/a2/bc/c8bc9cce8ec064558ae9b8ab2dbea9d5bdfbaf5c50f637a19cb120410b10/os-service-types-1.3.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/a2/bc/c8bc9cce8ec064558ae9b8ab2dbea9d5bdfbaf5c50f637a19cb120410b10/os-service-types-1.3.0.tar.gz
Summary  : Python library for consuming OpenStack sevice-types-authority data
Group    : Development/Tools
License  : Apache-2.0
Requires: os-service-types-python3
Requires: os-service-types-license
Requires: os-service-types-python
Requires: pbr
BuildRequires : buildreq-distutils3
BuildRequires : pbr

%description
os-service-types
        ================
        
        Python library for consuming OpenStack sevice-types-authority data
        
        The `OpenStack Service Types Authority`_ contains information about official
        OpenStack services and their historical ``service-type`` aliases.
        
        The data is in JSON and the latest data should always be used. This simple
        library exists to allow for easy consumption of the data, along with a built-in
        version of the data to use in case network access is for some reason not
        possible and local caching of the fetched data.

%package license
Summary: license components for the os-service-types package.
Group: Default

%description license
license components for the os-service-types package.


%package python
Summary: python components for the os-service-types package.
Group: Default
Requires: os-service-types-python3

%description python
python components for the os-service-types package.


%package python3
Summary: python3 components for the os-service-types package.
Group: Default
Requires: python3-core

%description python3
python3 components for the os-service-types package.


%prep
%setup -q -n os-service-types-1.3.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1533789094
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/os-service-types
cp LICENSE %{buildroot}/usr/share/doc/os-service-types/LICENSE
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(-,root,root,-)
/usr/share/doc/os-service-types/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
